
package com.bellotoaccess.vista;

import com.bellotoaccess.controlador.RegistroUser;
import com.bellotoaccess.modelo.Usuario;
import com.bellotoaccess.utils.Utils;
import com.bellotoaccess.vistaRegistro.*;
import javax.swing.JOptionPane;

/**
 *
 * @author coh_o
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPersona
//     */
    Usuario us=new Usuario();
    RegistroUser r=new RegistroUser();
    
    public RegistrarUsuario() {
        initComponents();
        Utils.cambiarIconoFrame(this);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpanel_us = new javax.swing.JPanel();
        jtxt_usId = new javax.swing.JTextField();
        JLbl_Icono = new javax.swing.JLabel();
        jtxt_usRun = new javax.swing.JTextField();
        jtxt_usNombre = new javax.swing.JTextField();
        jtxt_usApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtn_usLimpiar = new javax.swing.JButton();
        jbtn_usAnadir = new javax.swing.JButton();
        jbtn_usVolver = new javax.swing.JButton();
        jbtn_usModificar = new javax.swing.JButton();
        jbtn_usEliminar = new javax.swing.JButton();
        jtxt_usContrasena = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BellotoAccess - Sistema administrativo de Condominios");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel_us.setBackground(new java.awt.Color(245, 236, 228));

        jtxt_usId.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_usId.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_usId.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_usId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usIdActionPerformed(evt);
            }
        });
        jtxt_usId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_usIdKeyPressed(evt);
            }
        });

        JLbl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bellotoaccess/imag/pirncipalg.png"))); // NOI18N

        jtxt_usRun.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_usRun.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_usRun.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_usRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usRunActionPerformed(evt);
            }
        });
        jtxt_usRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_usRunKeyPressed(evt);
            }
        });

        jtxt_usNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_usNombre.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_usNombre.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_usNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usNombreActionPerformed(evt);
            }
        });
        jtxt_usNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_usNombreKeyPressed(evt);
            }
        });

        jtxt_usApellido.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_usApellido.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_usApellido.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_usApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_usApellidoActionPerformed(evt);
            }
        });
        jtxt_usApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_usApellidoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 91, 62));
        jLabel1.setText("ID");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 91, 62));
        jLabel4.setText("RUN");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 91, 62));
        jLabel5.setText("NOMBRE");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 91, 62));
        jLabel6.setText("APELLIDO");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(53, 91, 62));
        jLabel7.setText("CONTRASEÑA");

        jbtn_usLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_usLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_usLimpiar.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_usLimpiar.setText("LIMPIAR");
        jbtn_usLimpiar.setBorder(null);
        jbtn_usLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_usLimpiarActionPerformed(evt);
            }
        });

        jbtn_usAnadir.setBackground(new java.awt.Color(2, 150, 100));
        jbtn_usAnadir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_usAnadir.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_usAnadir.setText("AÑADIR");
        jbtn_usAnadir.setBorder(null);
        jbtn_usAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_usAnadirActionPerformed(evt);
            }
        });

        jbtn_usVolver.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_usVolver.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_usVolver.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_usVolver.setText("VOLVER");
        jbtn_usVolver.setBorder(null);
        jbtn_usVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_usVolverMouseClicked(evt);
            }
        });
        jbtn_usVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_usVolverActionPerformed(evt);
            }
        });

        jbtn_usModificar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_usModificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_usModificar.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_usModificar.setText("MODIFICAR");
        jbtn_usModificar.setBorder(null);
        jbtn_usModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_usModificarActionPerformed(evt);
            }
        });

        jbtn_usEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_usEliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_usEliminar.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_usEliminar.setText("ELIMINAR");
        jbtn_usEliminar.setBorder(null);
        jbtn_usEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_usEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_usLayout = new javax.swing.GroupLayout(jpanel_us);
        jpanel_us.setLayout(jpanel_usLayout);
        jpanel_usLayout.setHorizontalGroup(
            jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_usLayout.createSequentialGroup()
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_usLayout.createSequentialGroup()
                        .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_usLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel6)))
                            .addGroup(jpanel_usLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(47, 47, 47)
                        .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_usNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jtxt_usApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jtxt_usRun, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jtxt_usId, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(jtxt_usContrasena)))
                    .addGroup(jpanel_usLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_usLayout.createSequentialGroup()
                                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_usLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_usModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbtn_usVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_usAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtn_usEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLbl_Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(571, Short.MAX_VALUE))
        );
        jpanel_usLayout.setVerticalGroup(
            jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_usLayout.createSequentialGroup()
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_usLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jtxt_usId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_usLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_usRun, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_usNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_usApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_usContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_usLayout.createSequentialGroup()
                        .addComponent(jbtn_usEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_usAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_usModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpanel_usLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_usLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_usVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addComponent(JLbl_Icono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52))
        );

        jPanel2.add(jpanel_us, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1060, 510));

        jPanel3.setBackground(new java.awt.Color(53, 91, 62));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AÑADIR USUARIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel3)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_usIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usIdActionPerformed

    }//GEN-LAST:event_jtxt_usIdActionPerformed

    private void jtxt_usIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_usIdKeyPressed

    }//GEN-LAST:event_jtxt_usIdKeyPressed

    private void jtxt_usRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usRunActionPerformed

    private void jtxt_usRunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_usRunKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usRunKeyPressed

    private void jtxt_usNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usNombreActionPerformed

    private void jtxt_usNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_usNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usNombreKeyPressed

    private void jtxt_usApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_usApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usApellidoActionPerformed

    private void jtxt_usApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_usApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_usApellidoKeyPressed

    private void jbtn_usLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_usLimpiarActionPerformed
                this.jtxt_usId.setText("");
                this.jtxt_usRun.setText("");
                this.jtxt_usNombre.setText("");
                this.jtxt_usApellido.setText("");
                this.jtxt_usContrasena.setText("");
               
    }//GEN-LAST:event_jbtn_usLimpiarActionPerformed

    private void jbtn_usAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_usAnadirActionPerformed
                if (!this.jtxt_usId.getText().isBlank()) {
                    us=r.buscarPorId(Integer.parseInt(this.jtxt_usId.getText()));}
                        if (us.getId()==0) {
                        us.setId(Integer.parseInt(this.jtxt_usId.getText()));
                        us.setRun(this.jtxt_usRun.getText());
                        us.setNombre(this.jtxt_usNombre.getText());
                        us.setApellido(this.jtxt_usApellido.getText());
                        us.setContraseña(this.jtxt_usContrasena.getText());
                        if (r.agregarUsuario(us)) {
                            JOptionPane.showMessageDialog(rootPane, "Usuario agregado", "Añadir Usuario", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Error: usuario no agregado", "Añadir Usuario", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error: este usuario ya existe", "Añadir Usuario", JOptionPane.ERROR_MESSAGE);
                    }
                       
    }//GEN-LAST:event_jbtn_usAnadirActionPerformed

    private void jbtn_usVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_usVolverMouseClicked

    }//GEN-LAST:event_jbtn_usVolverMouseClicked

    private void jbtn_usVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_usVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_usVolverActionPerformed

    private void jbtn_usModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_usModificarActionPerformed
       if (!this.jtxt_usId.getText().isBlank()) {
                    us=r.buscarPorId(Integer.parseInt(this.jtxt_usId.getText()));
                        if (us.getId()!=0) {
                        us.setId(Integer.parseInt(this.jtxt_usId.getText()));
                        us.setRun(this.jtxt_usRun.getText());
                        us.setNombre(this.jtxt_usNombre.getText());
                        us.setApellido(this.jtxt_usApellido.getText());
                        us.setContraseña(this.jtxt_usContrasena.getText());
                        if (r.modificarUsuario(us)) {
                            JOptionPane.showMessageDialog(rootPane, "Usuario modificado", "Información", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Error: usuario no modificado", "Información", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error: este usuario No existe", "Información", JOptionPane.ERROR_MESSAGE);
          }
    }else{
           JOptionPane.showMessageDialog(rootPane, "Debe ingresar el id", "informacion", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jbtn_usModificarActionPerformed

    private void jbtn_usEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_usEliminarActionPerformed
      if (!this.jtxt_usId.getText().isBlank()) {
                    us=r.buscarPorId(Integer.parseInt(this.jtxt_usId.getText()));
                        if (us.getId()!=0) {
                        us.setId(Integer.parseInt(this.jtxt_usId.getText()));
                        if (r.eliminarUsuario(Integer.parseInt(this.jtxt_usId.getText()))) {
                            JOptionPane.showMessageDialog(rootPane, "Usuario eliminado", "Información", JOptionPane.INFORMATION_MESSAGE);
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Error: usuario no eliminado", "Información", JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Error: este usuario No existe", "Información", JOptionPane.ERROR_MESSAGE);
          }
    }else{
           JOptionPane.showMessageDialog(rootPane, "Debe ingresar el id", "informaicon", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jbtn_usEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbl_Icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_usAnadir;
    private javax.swing.JButton jbtn_usEliminar;
    private javax.swing.JButton jbtn_usLimpiar;
    private javax.swing.JButton jbtn_usModificar;
    private javax.swing.JButton jbtn_usVolver;
    private javax.swing.JPanel jpanel_us;
    private javax.swing.JTextField jtxt_usApellido;
    private javax.swing.JPasswordField jtxt_usContrasena;
    private javax.swing.JTextField jtxt_usId;
    private javax.swing.JTextField jtxt_usNombre;
    private javax.swing.JTextField jtxt_usRun;
    // End of variables declaration//GEN-END:variables
}
