/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bellotoaccess.vistaRegistro;

/**
 *
 * @author coh_o
 */
public class RegistrarPropietarioDepto extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPersona
     */
    public RegistrarPropietarioDepto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupEstado1 = new javax.swing.ButtonGroup();
        groupEstado2 = new javax.swing.ButtonGroup();
        groupEstado3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JLbl_Icono = new javax.swing.JLabel();
        jTxt_runUsuario1 = new javax.swing.JTextField();
        jTxt_runUsuario2 = new javax.swing.JTextField();
        JBtn_Modificar = new javax.swing.JButton();
        JBtn_Modificar1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTxt_runUsuario3 = new javax.swing.JTextField();
        jrbtn_disponible1 = new javax.swing.JRadioButton();
        jrbtn_noDisponible1 = new javax.swing.JRadioButton();
        jrbtn_disponible2 = new javax.swing.JRadioButton();
        jrbtn_noDisponible2 = new javax.swing.JRadioButton();
        jrbtn_disponible3 = new javax.swing.JRadioButton();
        jrbtn_noDisponible3 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 236, 228));

        JLbl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bellotoaccess/imag/pirncipalg.png"))); // NOI18N

        jTxt_runUsuario1.setBackground(new java.awt.Color(255, 255, 255));
        jTxt_runUsuario1.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jTxt_runUsuario1.setForeground(new java.awt.Color(153, 153, 153));
        jTxt_runUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_runUsuario1ActionPerformed(evt);
            }
        });
        jTxt_runUsuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxt_runUsuario1KeyPressed(evt);
            }
        });

        jTxt_runUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        jTxt_runUsuario2.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jTxt_runUsuario2.setForeground(new java.awt.Color(153, 153, 153));
        jTxt_runUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_runUsuario2ActionPerformed(evt);
            }
        });
        jTxt_runUsuario2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxt_runUsuario2KeyPressed(evt);
            }
        });

        JBtn_Modificar.setBackground(new java.awt.Color(255, 255, 255));
        JBtn_Modificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        JBtn_Modificar.setForeground(new java.awt.Color(53, 91, 62));
        JBtn_Modificar.setText("LIMPIAR");
        JBtn_Modificar.setBorder(null);
        JBtn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_ModificarActionPerformed(evt);
            }
        });

        JBtn_Modificar1.setBackground(new java.awt.Color(53, 91, 62));
        JBtn_Modificar1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        JBtn_Modificar1.setForeground(new java.awt.Color(255, 255, 255));
        JBtn_Modificar1.setText("AÑADIR");
        JBtn_Modificar1.setBorder(null);
        JBtn_Modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn_Modificar1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(53, 91, 62));
        jLabel9.setText("NUM. DEPTO 2");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(53, 91, 62));
        jLabel10.setText("NUM. DEPTO 1");

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(53, 91, 62));
        jLabel11.setText("NUM. DEPTO 3");

        jTxt_runUsuario3.setBackground(new java.awt.Color(255, 255, 255));
        jTxt_runUsuario3.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jTxt_runUsuario3.setForeground(new java.awt.Color(153, 153, 153));
        jTxt_runUsuario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_runUsuario3ActionPerformed(evt);
            }
        });
        jTxt_runUsuario3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxt_runUsuario3KeyPressed(evt);
            }
        });

        groupEstado1.add(jrbtn_disponible1);
        jrbtn_disponible1.setForeground(new java.awt.Color(53, 91, 62));
        jrbtn_disponible1.setText("Disponible");

        groupEstado1.add(jrbtn_noDisponible1);
        jrbtn_noDisponible1.setForeground(new java.awt.Color(53, 91, 62));
        jrbtn_noDisponible1.setText("No disponible");

        groupEstado2.add(jrbtn_disponible2);
        jrbtn_disponible2.setForeground(new java.awt.Color(53, 91, 62));
        jrbtn_disponible2.setText("Disponible");

        groupEstado2.add(jrbtn_noDisponible2);
        jrbtn_noDisponible2.setForeground(new java.awt.Color(53, 91, 62));
        jrbtn_noDisponible2.setText("No disponible");

        groupEstado3.add(jrbtn_disponible3);
        jrbtn_disponible3.setForeground(new java.awt.Color(53, 91, 62));
        jrbtn_disponible3.setText("Disponible");

        groupEstado3.add(jrbtn_noDisponible3);
        jrbtn_noDisponible3.setForeground(new java.awt.Color(53, 91, 62));
        jrbtn_noDisponible3.setText("No disponible");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBtn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtn_Modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(JLbl_Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbtn_disponible3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbtn_noDisponible3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbtn_disponible2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbtn_noDisponible2))
                            .addComponent(jTxt_runUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_runUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxt_runUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbtn_disponible1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jrbtn_noDisponible1)))))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTxt_runUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtn_disponible1)
                    .addComponent(jrbtn_noDisponible1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxt_runUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtn_disponible2)
                    .addComponent(jrbtn_noDisponible2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jTxt_runUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtn_disponible3)
                    .addComponent(jrbtn_noDisponible3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JBtn_Modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(JLbl_Icono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1060, 510));

        jPanel3.setBackground(new java.awt.Color(53, 91, 62));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AÑADIR DEPARTAMENTO PROPIETARIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel3)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxt_runUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_runUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_runUsuario1ActionPerformed

    private void jTxt_runUsuario1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_runUsuario1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_runUsuario1KeyPressed

    private void JBtn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_ModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_ModificarActionPerformed

    private void JBtn_Modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn_Modificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBtn_Modificar1ActionPerformed

    private void jTxt_runUsuario2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_runUsuario2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_runUsuario2KeyPressed

    private void jTxt_runUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_runUsuario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_runUsuario2ActionPerformed

    private void jTxt_runUsuario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_runUsuario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_runUsuario3ActionPerformed

    private void jTxt_runUsuario3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxt_runUsuario3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_runUsuario3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietarioDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietarioDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietarioDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietarioDepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPropietarioDepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_Modificar;
    private javax.swing.JButton JBtn_Modificar1;
    private javax.swing.JLabel JLbl_Icono;
    private javax.swing.ButtonGroup groupEstado1;
    private javax.swing.ButtonGroup groupEstado2;
    private javax.swing.ButtonGroup groupEstado3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTxt_runUsuario1;
    private javax.swing.JTextField jTxt_runUsuario2;
    private javax.swing.JTextField jTxt_runUsuario3;
    private javax.swing.JRadioButton jrbtn_disponible1;
    private javax.swing.JRadioButton jrbtn_disponible2;
    private javax.swing.JRadioButton jrbtn_disponible3;
    private javax.swing.JRadioButton jrbtn_noDisponible1;
    private javax.swing.JRadioButton jrbtn_noDisponible2;
    private javax.swing.JRadioButton jrbtn_noDisponible3;
    // End of variables declaration//GEN-END:variables
}
