/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.bellotoaccess.vistaRegistro;

/**
 *
 * @author coh_o
 */
public class RegistrarArrendatario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarPersona
     */
    public RegistrarArrendatario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtxt_arrenNumDepto = new javax.swing.JTextField();
        JLbl_Icono = new javax.swing.JLabel();
        jtxt_arrenRun = new javax.swing.JTextField();
        jtxt_arrenNombre = new javax.swing.JTextField();
        jtxt_arrenApellido = new javax.swing.JTextField();
        jtxt_arrenEmail = new javax.swing.JTextField();
        jtxt_arrenTelefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jbtn_limpiarArren = new javax.swing.JButton();
        jbtn_anadirArren = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        jtxt_arrenFecha = new javax.swing.JTextField();
        jbtn_cerrarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 236, 228));

        jtxt_arrenNumDepto.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenNumDepto.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenNumDepto.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenNumDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenNumDeptoActionPerformed(evt);
            }
        });
        jtxt_arrenNumDepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenNumDeptoKeyPressed(evt);
            }
        });

        JLbl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bellotoaccess/imag/pirncipalg.png"))); // NOI18N

        jtxt_arrenRun.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenRun.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenRun.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenRunActionPerformed(evt);
            }
        });
        jtxt_arrenRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenRunKeyPressed(evt);
            }
        });

        jtxt_arrenNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenNombre.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenNombre.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenNombreActionPerformed(evt);
            }
        });
        jtxt_arrenNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenNombreKeyPressed(evt);
            }
        });

        jtxt_arrenApellido.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenApellido.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenApellido.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenApellidoActionPerformed(evt);
            }
        });
        jtxt_arrenApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenApellidoKeyPressed(evt);
            }
        });

        jtxt_arrenEmail.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenEmail.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenEmail.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenEmailActionPerformed(evt);
            }
        });
        jtxt_arrenEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenEmailKeyPressed(evt);
            }
        });

        jtxt_arrenTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenTelefono.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenTelefonoActionPerformed(evt);
            }
        });
        jtxt_arrenTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenTelefonoKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 91, 62));
        jLabel1.setText("NUM. DEPTO");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 91, 62));
        jLabel4.setText("RUN");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 91, 62));
        jLabel5.setText("NOMBRE");

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 91, 62));
        jLabel6.setText("APELLIDO");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(53, 91, 62));
        jLabel7.setText("EMAIL");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(53, 91, 62));
        jLabel8.setText("TELÉFONO");

        jbtn_limpiarArren.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_limpiarArren.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_limpiarArren.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_limpiarArren.setText("LIMPIAR");
        jbtn_limpiarArren.setBorder(null);
        jbtn_limpiarArren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarArrenActionPerformed(evt);
            }
        });

        jbtn_anadirArren.setBackground(new java.awt.Color(2, 150, 100));
        jbtn_anadirArren.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_anadirArren.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_anadirArren.setText("AÑADIR");
        jbtn_anadirArren.setBorder(null);
        jbtn_anadirArren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_anadirArrenActionPerformed(evt);
            }
        });

        fecha.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(53, 91, 62));
        fecha.setText("FECHA");

        jtxt_arrenFecha.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_arrenFecha.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_arrenFecha.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_arrenFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_arrenFechaActionPerformed(evt);
            }
        });
        jtxt_arrenFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_arrenFechaKeyPressed(evt);
            }
        });

        jbtn_cerrarSesion.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_cerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_cerrarSesion.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_cerrarSesion.setText("VOLVER");
        jbtn_cerrarSesion.setBorder(null);
        jbtn_cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_cerrarSesionMouseClicked(evt);
            }
        });
        jbtn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtn_limpiarArren, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_anadirArren, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JLbl_Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxt_arrenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_arrenApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_arrenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_arrenRun, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_arrenNumDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(fecha)))
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxt_arrenFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxt_arrenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4))
                            .addComponent(jLabel1))))
                .addContainerGap(581, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtxt_arrenNumDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jtxt_arrenRun, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addComponent(jtxt_arrenNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(jtxt_arrenApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_arrenEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxt_arrenTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxt_arrenFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_anadirArren, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_limpiarArren, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_cerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addComponent(JLbl_Icono, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(52, 52, 52))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1060, 510));

        jPanel3.setBackground(new java.awt.Color(53, 91, 62));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AÑADIR ARRENDATARIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel3)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_arrenNumDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenNumDeptoActionPerformed

    }//GEN-LAST:event_jtxt_arrenNumDeptoActionPerformed

    private void jtxt_arrenNumDeptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenNumDeptoKeyPressed

    }//GEN-LAST:event_jtxt_arrenNumDeptoKeyPressed

    private void jtxt_arrenRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenRunActionPerformed

    private void jtxt_arrenRunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenRunKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenRunKeyPressed

    private void jtxt_arrenNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenNombreActionPerformed

    private void jtxt_arrenNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenNombreKeyPressed

    private void jtxt_arrenApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenApellidoActionPerformed

    private void jtxt_arrenApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenApellidoKeyPressed

    private void jtxt_arrenEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenEmailActionPerformed

    private void jtxt_arrenEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenEmailKeyPressed

    private void jtxt_arrenTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenTelefonoActionPerformed

    private void jtxt_arrenTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenTelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenTelefonoKeyPressed

    private void jbtn_limpiarArrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarArrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_limpiarArrenActionPerformed

    private void jbtn_anadirArrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_anadirArrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_anadirArrenActionPerformed

    private void jtxt_arrenFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_arrenFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenFechaActionPerformed

    private void jtxt_arrenFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_arrenFechaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_arrenFechaKeyPressed

    private void jbtn_cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_cerrarSesionMouseClicked

    }//GEN-LAST:event_jbtn_cerrarSesionMouseClicked

    private void jbtn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cerrarSesionActionPerformed

    }//GEN-LAST:event_jbtn_cerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarArrendatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarArrendatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarArrendatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarArrendatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarArrendatario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbl_Icono;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_anadirArren;
    private javax.swing.JButton jbtn_cerrarSesion;
    private javax.swing.JButton jbtn_limpiarArren;
    private javax.swing.JTextField jtxt_arrenApellido;
    private javax.swing.JTextField jtxt_arrenEmail;
    private javax.swing.JTextField jtxt_arrenFecha;
    private javax.swing.JTextField jtxt_arrenNombre;
    private javax.swing.JTextField jtxt_arrenNumDepto;
    private javax.swing.JTextField jtxt_arrenRun;
    private javax.swing.JTextField jtxt_arrenTelefono;
    // End of variables declaration//GEN-END:variables
}
