
package com.bellotoaccess.vistaRegistro;

import com.bellotoaccess.controlador.RegistroPropietario;
import com.bellotoaccess.modelo.Propietario;
import com.bellotoaccess.utils.Utils;
import javax.swing.JOptionPane;

/**
 *
 * @author Cristian Olivares
 */
public class RegistrarPropietario extends javax.swing.JFrame {

    Propietario pr=new Propietario();
    RegistroPropietario r=new RegistroPropietario();
    public RegistrarPropietario() {
        initComponents();
        Utils.cambiarIconoFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        JLbl_Icono = new javax.swing.JLabel();
        jbtn_prVolver = new javax.swing.JButton();
        jbtn_prEliminar = new javax.swing.JButton();
        jbtn_prModificar = new javax.swing.JButton();
        jbtn_prLimpiar = new javax.swing.JButton();
        jbtn_prAnadir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtxt_prId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtxt_prNumDepto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_prRun = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_prNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxt_prApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxt_prEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_prTelefono = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BellotoAccess - Sistema administrativo de Condominios");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 236, 228));

        JLbl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/bellotoaccess/imag/pirncipalg.png"))); // NOI18N

        jbtn_prVolver.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_prVolver.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_prVolver.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_prVolver.setText("VOLVER");
        jbtn_prVolver.setBorder(null);
        jbtn_prVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtn_prVolverMouseClicked(evt);
            }
        });
        jbtn_prVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_prVolverActionPerformed(evt);
            }
        });

        jbtn_prEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_prEliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_prEliminar.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_prEliminar.setText("ELIMINAR");
        jbtn_prEliminar.setBorder(null);
        jbtn_prEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_prEliminarActionPerformed(evt);
            }
        });

        jbtn_prModificar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_prModificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_prModificar.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_prModificar.setText("MODIFICAR");
        jbtn_prModificar.setBorder(null);
        jbtn_prModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_prModificarActionPerformed(evt);
            }
        });

        jbtn_prLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_prLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_prLimpiar.setForeground(new java.awt.Color(53, 91, 62));
        jbtn_prLimpiar.setText("LIMPIAR");
        jbtn_prLimpiar.setBorder(null);
        jbtn_prLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_prLimpiarActionPerformed(evt);
            }
        });

        jbtn_prAnadir.setBackground(new java.awt.Color(2, 150, 100));
        jbtn_prAnadir.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jbtn_prAnadir.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_prAnadir.setText("AÑADIR");
        jbtn_prAnadir.setBorder(null);
        jbtn_prAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_prAnadirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(53, 91, 62));
        jLabel9.setText("ID");

        jtxt_prId.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prId.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prId.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prIdActionPerformed(evt);
            }
        });
        jtxt_prId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prIdKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 91, 62));
        jLabel1.setText("NUM. DEPTO");

        jtxt_prNumDepto.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prNumDepto.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prNumDepto.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prNumDepto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prNumDeptoActionPerformed(evt);
            }
        });
        jtxt_prNumDepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prNumDeptoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 91, 62));
        jLabel4.setText("RUN");

        jtxt_prRun.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prRun.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prRun.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prRunActionPerformed(evt);
            }
        });
        jtxt_prRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prRunKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(53, 91, 62));
        jLabel5.setText("NOMBRE");

        jtxt_prNombre.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prNombre.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prNombre.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prNombreActionPerformed(evt);
            }
        });
        jtxt_prNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prNombreKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(53, 91, 62));
        jLabel6.setText("APELLIDO");

        jtxt_prApellido.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prApellido.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prApellido.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prApellidoActionPerformed(evt);
            }
        });
        jtxt_prApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prApellidoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(53, 91, 62));
        jLabel7.setText("EMAIL");

        jtxt_prEmail.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prEmail.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prEmail.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prEmailActionPerformed(evt);
            }
        });
        jtxt_prEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prEmailKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(53, 91, 62));
        jLabel8.setText("TELÉFONO");

        jtxt_prTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jtxt_prTelefono.setFont(new java.awt.Font("Dubai", 0, 12)); // NOI18N
        jtxt_prTelefono.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_prTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_prTelefonoActionPerformed(evt);
            }
        });
        jtxt_prTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_prTelefonoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel8))
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_prTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_prNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_prApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_prEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_prRun, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_prNumDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_prId, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_prLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_prModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbtn_prAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtn_prVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jbtn_prEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JLbl_Icono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_prId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_prNumDepto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_prRun, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jtxt_prNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_prApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxt_prEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_prTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_prEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_prAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_prModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_prLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn_prVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JLbl_Icono))
                .addGap(62, 62, 62))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1060, 510));

        jPanel3.setBackground(new java.awt.Color(53, 91, 62));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AÑADIR PROPIETARIO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel3)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_prAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_prAnadirActionPerformed
        if (!this.jtxt_prId.getText().isBlank()) {
            pr=r.buscarPorIdPr(Integer.parseInt(this.jtxt_prId.getText()));}
        if (pr.getId()==0) {
            pr.setId(Integer.parseInt(this.jtxt_prId.getText()));
            pr.setDeptowner(Integer.parseInt(this.jtxt_prNumDepto.getText()));
            pr.setRun(this.jtxt_prRun.getText());
            pr.setNombre(this.jtxt_prNombre.getText());
            pr.setApellido(this.jtxt_prApellido.getText());
            pr.setEmail(this.jtxt_prEmail.getText());
            pr.setTelef(Integer.parseInt(this.jtxt_prTelefono.getText()));
            if (r.agregarPropietario(pr)) {
                JOptionPane.showMessageDialog(rootPane, "Propietario agregado", "Añadir Usuario", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error: Propietario no agregado", "Añadir Usuario", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Error: este Propietario ya existe", "Añadir Usuario", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtn_prAnadirActionPerformed

    private void jbtn_prLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_prLimpiarActionPerformed
        this.jtxt_prId.setText("");
        this.jtxt_prNumDepto.setText("");
        this.jtxt_prRun.setText("");
        this.jtxt_prNombre.setText("");
        this.jtxt_prApellido.setText("");
        this.jtxt_prEmail.setText("");
        this.jtxt_prTelefono.setText("");
    }//GEN-LAST:event_jbtn_prLimpiarActionPerformed

    private void jbtn_prModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_prModificarActionPerformed
        if (!this.jtxt_prId.getText().isBlank()) {
            pr=r.buscarPorIdPr(Integer.parseInt(this.jtxt_prId.getText()));
            if (pr.getId()!=0) {
                pr.setId(Integer.parseInt(this.jtxt_prId.getText()));
                pr.setDeptowner(Integer.parseInt(this.jtxt_prNumDepto.getText()));
                pr.setRun(this.jtxt_prRun.getText());
                pr.setNombre(this.jtxt_prNombre.getText());
                pr.setApellido(this.jtxt_prApellido.getText());
                pr.setEmail(this.jtxt_prEmail.getText());
                pr.setTelef(Integer.parseInt(this.jtxt_prTelefono.getText()));
                if (r.modificarPropietario(pr)) {
                    JOptionPane.showMessageDialog(rootPane, "Propietario modificado", "Información", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Error: Propietario no modificado", "Información", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error: este Propietario No existe", "Información", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el id", "Información", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jbtn_prModificarActionPerformed

    private void jbtn_prEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_prEliminarActionPerformed
        if (!this.jtxt_prId.getText().isBlank()) {
            pr=r.buscarPorIdPr(Integer.parseInt(this.jtxt_prId.getText()));
            if (pr.getId()!=0) {
                pr.setId(Integer.parseInt(this.jtxt_prId.getText()));
                if (r.eliminarPropietario(Integer.parseInt(this.jtxt_prId.getText()))) {
                    JOptionPane.showMessageDialog(rootPane, "Propietario eliminado", "Información", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Error: Propietario no eliminado", "Información", JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Error: este Propietario No existe", "Información", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar el id", "Información", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_jbtn_prEliminarActionPerformed

    private void jbtn_prVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_prVolverActionPerformed
        dispose();
    }//GEN-LAST:event_jbtn_prVolverActionPerformed

    private void jbtn_prVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtn_prVolverMouseClicked

    }//GEN-LAST:event_jbtn_prVolverMouseClicked

    private void jtxt_prIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prIdActionPerformed

    private void jtxt_prIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prIdKeyPressed

    private void jtxt_prNumDeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prNumDeptoActionPerformed

    }//GEN-LAST:event_jtxt_prNumDeptoActionPerformed

    private void jtxt_prNumDeptoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prNumDeptoKeyPressed

    }//GEN-LAST:event_jtxt_prNumDeptoKeyPressed

    private void jtxt_prRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prRunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prRunActionPerformed

    private void jtxt_prRunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prRunKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prRunKeyPressed

    private void jtxt_prNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prNombreActionPerformed

    private void jtxt_prNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prNombreKeyPressed

    private void jtxt_prApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prApellidoActionPerformed

    private void jtxt_prApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prApellidoKeyPressed

    private void jtxt_prEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prEmailActionPerformed

    private void jtxt_prEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prEmailKeyPressed

    private void jtxt_prTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_prTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prTelefonoActionPerformed

    private void jtxt_prTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_prTelefonoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_prTelefonoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPropietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPropietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbl_Icono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtn_prAnadir;
    private javax.swing.JButton jbtn_prEliminar;
    private javax.swing.JButton jbtn_prLimpiar;
    private javax.swing.JButton jbtn_prModificar;
    private javax.swing.JButton jbtn_prVolver;
    private javax.swing.JTextField jtxt_prApellido;
    private javax.swing.JTextField jtxt_prEmail;
    private javax.swing.JTextField jtxt_prId;
    private javax.swing.JTextField jtxt_prNombre;
    private javax.swing.JTextField jtxt_prNumDepto;
    private javax.swing.JTextField jtxt_prRun;
    private javax.swing.JTextField jtxt_prTelefono;
    // End of variables declaration//GEN-END:variables
}
